---

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**/*.rst'
      - '**/*.md'
    branches:
      - master
      - '[0-9].[0-9]'
  pull_request:
    branches:
      - master
      - '[0-9].[0-9]'
  schedule:
    - cron: '0 1 * * *' # nightly build


name: Integration

jobs:
  build_and_test:
    services:
      redisgears:
        image: redislabs/redisgears:1.2.5
        ports:
          - 6379:6379
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: setup/python@v4
        with:
          python-version: "3.10"
      - name: install
        run: |
          pip install --upgrade pip poetry tox
          poetry config virtualenvs.create false
      - name: build sdist and wheels
        run: |
          poetry build

      - name: run tests
        run: |
          tox -e tests
